name: MortisHeads
version: '${project.version}'
main: me.none030.mortisheads.MortisHeads
api-version: 1.13
softdepend:
  - CrackShot
  - WeaponMechanics
commands:
  heads:
    aliases:
      - mortisheads
