heads:
  NOTCH:
    name: "Notch"
    texture: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZjU2MDc2MzI4N2E3Zjk4NzE1MmMxYTM3NDA4Y2JmMzRlYmNlMDg0YzM3MTM2NmFmMmE3M2Y3ZjY5Mzc3ZDk3OSJ9fX0=
    lore:
      - "Notch Head"
    effects:
      NIGHT_VISION:
        duration: 10
        amplifier: 0
        ambient: true
        particles: true
        icon: true
      FIRE_RESISTANCE:
        duration: 3
        amplifier: 0
        ambient: true
        particles: true
        icon: true
    stays-on-after-death: true
  JAWA:
    name: "Jawa"
    texture: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZGQ5MTdiNTFlNDYyMzA1Yzc3NjczNTM3MGQ4MmQ3MmNmOTU5Njg1MmRmMWM0YmI5ODNmMmViMDIwYTRlNjg1NyJ9fX0=
    lore:
      - "Jawa Head"
    enchants:
      - PROTECTION_ENVIRONMENTAL:4
    flags:
      - HIDE_ENCHANTS
    effects:
      NIGHT_VISION:
        duration: 10
        amplifier: 0
        ambient: true
        particles: true
        icon: true
      FIRE_RESISTANCE:
        duration: 3
        amplifier: 0
        ambient: true
        particles: true
        icon: true
    stays-on-after-death: true
